# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jbkim/algorithm_jbkim/test_read

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jbkim/algorithm_jbkim/test_read

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jbkim/algorithm_jbkim/test_read/CMakeFiles /home/jbkim/algorithm_jbkim/test_read/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jbkim/algorithm_jbkim/test_read/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named opencv_read_evd

# Build rule for target.
opencv_read_evd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opencv_read_evd
.PHONY : opencv_read_evd

# fast build rule for target.
opencv_read_evd/fast:
	$(MAKE) -f CMakeFiles/opencv_read_evd.dir/build.make CMakeFiles/opencv_read_evd.dir/build
.PHONY : opencv_read_evd/fast

opencv_read_evd.o: opencv_read_evd.cpp.o

.PHONY : opencv_read_evd.o

# target to build an object file
opencv_read_evd.cpp.o:
	$(MAKE) -f CMakeFiles/opencv_read_evd.dir/build.make CMakeFiles/opencv_read_evd.dir/opencv_read_evd.cpp.o
.PHONY : opencv_read_evd.cpp.o

opencv_read_evd.i: opencv_read_evd.cpp.i

.PHONY : opencv_read_evd.i

# target to preprocess a source file
opencv_read_evd.cpp.i:
	$(MAKE) -f CMakeFiles/opencv_read_evd.dir/build.make CMakeFiles/opencv_read_evd.dir/opencv_read_evd.cpp.i
.PHONY : opencv_read_evd.cpp.i

opencv_read_evd.s: opencv_read_evd.cpp.s

.PHONY : opencv_read_evd.s

# target to generate assembly for a file
opencv_read_evd.cpp.s:
	$(MAKE) -f CMakeFiles/opencv_read_evd.dir/build.make CMakeFiles/opencv_read_evd.dir/opencv_read_evd.cpp.s
.PHONY : opencv_read_evd.cpp.s

opencv_read_evd_func.o: opencv_read_evd_func.cpp.o

.PHONY : opencv_read_evd_func.o

# target to build an object file
opencv_read_evd_func.cpp.o:
	$(MAKE) -f CMakeFiles/opencv_read_evd.dir/build.make CMakeFiles/opencv_read_evd.dir/opencv_read_evd_func.cpp.o
.PHONY : opencv_read_evd_func.cpp.o

opencv_read_evd_func.i: opencv_read_evd_func.cpp.i

.PHONY : opencv_read_evd_func.i

# target to preprocess a source file
opencv_read_evd_func.cpp.i:
	$(MAKE) -f CMakeFiles/opencv_read_evd.dir/build.make CMakeFiles/opencv_read_evd.dir/opencv_read_evd_func.cpp.i
.PHONY : opencv_read_evd_func.cpp.i

opencv_read_evd_func.s: opencv_read_evd_func.cpp.s

.PHONY : opencv_read_evd_func.s

# target to generate assembly for a file
opencv_read_evd_func.cpp.s:
	$(MAKE) -f CMakeFiles/opencv_read_evd.dir/build.make CMakeFiles/opencv_read_evd.dir/opencv_read_evd_func.cpp.s
.PHONY : opencv_read_evd_func.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... opencv_read_evd"
	@echo "... opencv_read_evd.o"
	@echo "... opencv_read_evd.i"
	@echo "... opencv_read_evd.s"
	@echo "... opencv_read_evd_func.o"
	@echo "... opencv_read_evd_func.i"
	@echo "... opencv_read_evd_func.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

